### ISSUE TITLE
Неверно генерируется валидатор паттерна из openapi контракта

### ISSUE THREAD

**Issue by SHADOWDANCH** [kora-projects/kora#90]
Если указать в openapi контракте паттерн валидации параметра проект не компилируется.

Часть openapi контракта
```yaml
      parameters:
        - name: in_token
          in: query
          required: true
          schema:
            type: string
            pattern: '^[A-Z]{1,6}$'
```

Часть сгенерированного контроллера
```kotlin
      @ru.tinkoff.kora.validation.common.annotation.Pattern("^[A-Z]{1,6}$")
      @ru.tinkoff.kora.http.common.annotation.Query("in_token")
      inToken: String,
```
Часть сгенерированного валидатор
```
    this.validator1 = patternValidatorFactory1.create(^[A-Z]{1,6}$, 0)
    this.validator2 = patternValidatorFactory1.create(^[a-zA-Z_]*$, 0)
```
В валидаторе нету кавычек на патернах, код не компилируется.
